releases:
 - name:
   chart: charts/devopsapp
   values:
     - values/frontend-values.yml

 - name:
   chart: charts/devopsapp
   values:
     - values/backend-values.yml   

 - name:
   chart: charts/ingress
   values:
     - values/ingress-values.yml 