apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: devopsapp
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Backend API
      - path: /api/hello
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.backend}}
            port:
              number: {{ .Values.service.backendPort }}

      # Frontend (all other paths)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.service.frontend}}
            port:
              number: {{ .Values.service.frontendPort }}            