{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{.name}}
  namespace: {{$.Values.namespace}}
spec:
  selector:
    app: {{.name}}
  ports:
    - port: {{.port}}
      targetPort: {{.Serviceport}}
  type: {{.Serviceporttyp}}
---
{{- end }}